version: "3.9"

services:
  db:
    image: postgres:16
    container_name: github-farm-db
    env_file: backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: ./backend
    entrypoint: ./entrypoint.sh
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - ./backend:/backend
      - bundle:/usr/local/bundle
    ports:
      - "3001:3001"
    depends_on:
      - db
      - redis
    env_file: backend/.env

  sidekiq:
    build: ./backend
    entrypoint: ./entrypoint.sh
    command: bundle exec sidekiq
    volumes:
      - ./backend:/backend
      - bundle:/usr/local_bundle
    depends_on:
      - db
      - redis
    env_file: backend/.env

volumes:
  postgres-data:
  bundle:
